/**
 * types-db.ts
 * 
 * Direct database table mappings for Supabase schema.
 * These interfaces match EXACTLY the SQL schema (snake_case, individual fields).
 * 
 * For business logic, use types.ts interfaces.
 * Use mappers.ts to transform between DB and business types.
 * 
 * @see supabase-schema.sql for table definitions
 * @see types.ts for business logic types
 * @see services/mappers.ts for transformation functions
 */

// ============================================================================
// ENUMS (matching SQL CREATE TYPE statements)
// ============================================================================

export type UserRoleDB = 'Admin' | 'User';

export type DealStageDB = 
  | 'Prospecting' 
  | 'Qualification' 
  | 'Proposal' 
  | 'Negotiation' 
  | 'Closed Won' 
  | 'Closed Lost';

export type TaskStatusDB = 'A Fazer' | 'Em Andamento' | 'Concluída';

export type TaskPriorityDB = 'Alta' | 'Média' | 'Baixa';

// ============================================================================
// TABLE: public.profiles
// ============================================================================

/**
 * Direct mapping of public.profiles table
 * Linked to Supabase auth.users
 */
export interface ProfileDB {
  id: string;                    // UUID PRIMARY KEY REFERENCES auth.users(id)
  name: string | null;           // TEXT
  email: string | null;          // TEXT UNIQUE
  role: UserRoleDB;              // public."UserRole" DEFAULT 'User'
  status: string;                // TEXT DEFAULT 'Ativo'
  last_login: string | null;     // TIMESTAMPTZ
  email_usage_gb: number;        // NUMERIC DEFAULT 0
  created_at: string;            // TIMESTAMPTZ DEFAULT NOW()
}

// ============================================================================
// TABLE: public.empresas
// ============================================================================

/**
 * Direct mapping of public.empresas table
 * Note: Endereço fields are INDIVIDUAL columns, not nested object
 * Note: CNAE fields are INDIVIDUAL columns, not nested object
 * Note: Sócios are in separate tables (socios + empresa_socios)
 */
export interface EmpresaDB {
  cnpj: string;                           // TEXT PRIMARY KEY
  razao_social: string;                   // TEXT NOT NULL
  nome_fantasia: string | null;           // TEXT
  situacao_cadastral: string | null;      // TEXT
  data_abertura: string | null;           // DATE
  porte: string | null;                   // TEXT
  
  // Endereço fields (individual, NOT nested object)
  logradouro: string | null;              // TEXT
  numero: string | null;                  // TEXT
  bairro: string | null;                  // TEXT
  cidade: string | null;                  // TEXT
  uf: string | null;                      // TEXT
  cep: string | null;                     // TEXT
  latitude: number | null;                // DOUBLE PRECISION
  longitude: number | null;               // DOUBLE PRECISION
  
  // CNAE fields (individual, NOT nested object)
  cnae_principal_codigo: string | null;   // TEXT
  cnae_principal_descricao: string | null; // TEXT
  
  // Arrays
  telefones: string[];                    // TEXT[]
  emails: string[];                       // TEXT[]
  
  created_at: string;                     // TIMESTAMPTZ DEFAULT NOW()
}

// ============================================================================
// TABLE: public.socios
// ============================================================================

/**
 * Direct mapping of public.socios table
 * Only stores unique sócio records (cpf_parcial + nome_socio)
 * Relationship with empresas is in empresa_socios table
 */
export interface SocioDB {
  cpf_parcial: string;  // TEXT PRIMARY KEY
  nome_socio: string;   // TEXT NOT NULL
}

// ============================================================================
// TABLE: public.empresa_socios
// ============================================================================

/**
 * Direct mapping of public.empresa_socios table
 * Junction table for Empresa <-> Sócio many-to-many relationship
 */
export interface EmpresaSocioDB {
  id: number;                           // BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
  empresa_cnpj: string;                 // TEXT REFERENCES empresas(cnpj)
  socio_cpf_parcial: string;            // TEXT REFERENCES socios(cpf_parcial)
  qualificacao: string | null;          // TEXT
  percentual_capital: number | null;    // NUMERIC
}

// ============================================================================
// TABLE: public.deals
// ============================================================================

/**
 * Direct mapping of public.deals table
 * Note: health is stored as 3 separate fields, not nested object
 */
export interface DealDB {
  id: string;                       // UUID PRIMARY KEY DEFAULT gen_random_uuid()
  company_name: string;             // TEXT NOT NULL
  contact_name: string | null;      // TEXT
  contact_email: string | null;     // TEXT
  value: number;                    // NUMERIC NOT NULL
  probability: number;              // NUMERIC DEFAULT 0
  stage: DealStageDB;               // public."DealStage" NOT NULL
  expected_close_date: string | null; // DATE
  last_activity: string;            // TIMESTAMPTZ DEFAULT NOW()
  
  // Foreign keys
  empresa_cnpj: string | null;      // TEXT REFERENCES empresas(cnpj)
  owner_id: string | null;          // UUID REFERENCES profiles(id)
  
  // Health fields (stored individually, not as object)
  health_score: number | null;            // NUMERIC
  health_reasoning: string | null;        // TEXT
  health_suggested_action: string | null; // TEXT
  
  created_at: string;               // TIMESTAMPTZ DEFAULT NOW()
}

// ============================================================================
// TABLE: public.tasks
// ============================================================================

/**
 * Direct mapping of public.tasks table
 */
export interface TaskDB {
  id: string;                           // UUID PRIMARY KEY DEFAULT gen_random_uuid()
  title: string;                        // TEXT NOT NULL
  due_date: string | null;              // DATE
  priority: TaskPriorityDB;             // public."TaskPriority" NOT NULL
  status: TaskStatusDB;                 // public."TaskStatus" NOT NULL
  description: string | null;           // TEXT
  google_calendar_event_id: string | null; // TEXT
  
  // Foreign keys
  deal_id: string | null;               // UUID REFERENCES deals(id)
  related_deal_name: string | null;     // TEXT
  assignee_id: string | null;           // UUID REFERENCES profiles(id)
  
  created_at: string;                   // TIMESTAMPTZ DEFAULT NOW()
}

// ============================================================================
// TABLE: public.indicacoes
// ============================================================================

/**
 * Direct mapping of public.indicacoes table
 */
export interface IndicacaoDB {
  id: string;                       // UUID PRIMARY KEY DEFAULT gen_random_uuid()
  empresa_nome: string;             // TEXT NOT NULL
  status: string;                   // TEXT NOT NULL DEFAULT 'Em negociação'
  data_indicacao: string;           // TIMESTAMPTZ DEFAULT NOW()
  recompensa_ganha: number;         // NUMERIC DEFAULT 0
  
  // Foreign keys
  indicador_id: string | null;      // UUID REFERENCES profiles(id)
  empresa_cnpj: string | null;      // TEXT REFERENCES empresas(cnpj)
}

// ============================================================================
// HELPER TYPES
// ============================================================================

/**
 * Generic API response wrapper
 * Standardizes all API responses with data/error/metadata
 */
export interface ApiResponse<T> {
  data: T | null;
  error: string | null;
  metadata?: {
    total?: number;
    page?: number;
    limit?: number;
    timestamp?: string;
  };
}

/**
 * Paginated response wrapper
 */
export interface PaginatedResponse<T> {
  data: T[];
  pagination: {
    total: number;
    page: number;
    limit: number;
    totalPages: number;
  };
  error: string | null;
}

/**
 * JOIN result: Sócio with empresa relationship data
 * Combines data from socios + empresa_socios tables
 */
export interface SocioComEmpresaDB {
  // From socios table
  cpf_parcial: string;
  nome_socio: string;
  
  // From empresa_socios table
  empresa_cnpj: string;
  qualificacao: string | null;
  percentual_capital: number | null;
}

/**
 * JOIN result: Empresa with full sócios data
 * Combines EmpresaDB + array of SocioComEmpresaDB
 */
export interface EmpresaComSociosDB extends EmpresaDB {
  socios: SocioComEmpresaDB[];
}

/**
 * Type guard to check if a value is a valid UUID
 */
export function isValidUUID(value: string): boolean {
  const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
  return uuidRegex.test(value);
}

/**
 * Type guard to check if a value is a valid CNPJ
 */
export function isValidCNPJ(value: string): boolean {
  // Remove non-numeric characters
  const cnpj = value.replace(/\D/g, '');
  return cnpj.length === 14;
}
